# Sistemas Lineares

implementações

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Substituição Retroativa


$$
\begin{cases}
    2 x_1 + 3 x_2 -1 x_3 =5\\\\
    0 x_1 -2x_2 -1x_3 =-7\\\\
    0 x_1 + 0 x_2 +5x_3  =15
\end{cases}
$$

$$A\cdot x = b$$

$$
\left(\begin{array}{cc} 
2 & 3 & -1 \\
0 &-2 & -1 \\
0 & 0 & 5 
\end{array}\right)
\left(\begin{array}{c} 
x_1\\ 
x_2\\
x_3
\end{array}\right)
=
\left(\begin{array}{c} 
5\\ 
-7\\
15
\end{array}\right)
$$ 


In [7]:
"""
A - matriz extendida
nEq - ordem da matriz
nL - num linhas
nC - num colunas
x - solução
"""
def sretro(A):
    nC = len(A[0])
    nEq = nC-1
    b = [row[nC-1] for row in A]
    x = np.zeros(nEq)
    for i in range(nEq,0,-1):
        I = i-1
        x[I]=b[I]
        sumRes = 0
        #aux = "x[{0}] = b[{0}] - (".format(I)
        for j in range(i,nEq):
         #   aux += "A[{0}][{1}]*x[{1}]".format(I,j)
            sumRes = sumRes + A[I][j]*x[j]
        #aux += ') / A[{0}][{0}]'.format(I)
        #print(aux)
        if(A[I][I] != 0):
            x[I] = (x[I]-sumRes)/A[I][I]
        elif(x[I]-sumRes != 0):
            raise Exception("Impossible system")
        else:
            raise Exception("Indeterminate system")
    return x

In [8]:
#main
A = np.loadtxt('solve_sretro.txt')
N = len(A[0])-1
print(A)
for i in range(len(A)):
    for j in range(len(A[0])):
        if(j < len(A[0])-1):
            print('{0}X{1}+'.format(A[i][j],j+1), end=' ')
        else:
            print(' = ',A[i][j], end=' ')
    print('\n')

res = sretro(A)
print(res)

[[ 2.  3. -1.  5.]
 [ 0. -2. -1. -7.]
 [ 0.  0.  5. 15.]]
2.0X1+ 3.0X2+ -1.0X3+  =  5.0 

0.0X1+ -2.0X2+ -1.0X3+  =  -7.0 

0.0X1+ 0.0X2+ 5.0X3+  =  15.0 

[1. 2. 3.]


## Método de Gauss sem pivoteamento


$$
\begin{cases}
    2 x_1 + 3 x_2 -1 x_3 =5\\\\
    4 x_1 + 4 x_2 -3 x_3 =3\\\\
    2 x_1 - 3 x_2 +1 x_3  =-1
\end{cases}
$$

$$A\cdot x = b$$

$$
\left(\begin{array}{cc} 
2 & 3 & -1 \\
4 & 4 & -3 \\
1 & -3 & 1 
\end{array}\right)
\left(\begin{array}{c} 
x_1\\ 
x_2\\
x_3
\end{array}\right)
=
\left(\begin{array}{c} 
5\\ 
3\\
-1
\end{array}\right)
$$ 



In [19]:
"""
A - matriz extendida
nEq - ordem da matriz
nL - num linhas
nC - num colunas
x - solução
"""
def gauss(A):
    nL= len(A)
    nC = len(A[0])
    nEq = nC-1
    posPivo=0
    for i in range(0,nEq-1):
        pivo = A[i][i]
        posPivo=i
        # calc multiples
        m = np.zeros(nL)
        for k in range(i+1,nL):
#            print('m[{0}] = - A[{0}][{1}]/A[{0}][{0}]'.format(k,0),"= -{0}/{1}".format(A[k][0],pivo))
            m[k] = - A[k][posPivo]/pivo
        # Operações
        for j in range(posPivo+1,nL):
            #print('L({0})={1}, m({0})={2}'.format(j,A[j],m[j]))
            A[j] = m[j]*A[posPivo]+A[j]
    return A
        

In [21]:
A = np.loadtxt('ex_gauss.txt')
print(A)
res = gauss(A)
sretro(res)

[[ 2.  3. -1.  5.]
 [ 4.  4. -3.  3.]
 [ 2. -3.  1. -1.]]


array([1., 2., 3.])

## Gauss com pivoteamento

In [25]:
"""
A - matriz extendida
nEq - ordem da matriz
nL - num linhas
nC - num colunas
x - solução
"""
def gauss(A):
    nL= len(A)
    nC = len(A[0])
    nEq = nC-1
    posPivo=0
    for i in range(0,nEq-1):
        pivo = A[i][i]
        #pivoteamento #max([row[i] for row in A])
        maior = max([row[i] for row in A])
        print("M:",maior)
        if(pivo <  maior):
            for l in range(i,nL):
                if(A[l][i] > pivo):
                    A[i],A[l] = A[l],A[i]
                    print(A)
                    pivo = A[i][i]
        posPivo=i
        # calc multiples
        m = np.zeros(nL)
        for k in range(i+1,nL):
#            print('m[{0}] = - A[{0}][{1}]/A[{0}][{0}]'.format(k,0),"= -{0}/{1}".format(A[k][0],pivo))
            m[k] = - A[k][posPivo]/pivo
        # Operações
        for j in range(posPivo+1,nL):
            #print('L({0})={1}, m({0})={2}'.format(j,A[j],m[j]))
            A[j] = m[j]*A[posPivo]+A[j]
    return A
        

In [26]:
A = np.loadtxt('solve_sretro.txt')
print(A)
gauss(A)

[[ 3. -4.  1.  9.]
 [ 1.  2.  2.  3.]
 [ 4.  0. -3. -2.]]
M: 4.0
[[ 4.  0. -3. -2.]
 [ 1.  2.  2.  3.]
 [ 4.  0. -3. -2.]]
M: 2.0


array([[ 4.  ,  0.  , -3.  , -2.  ],
       [ 0.  ,  2.  ,  2.75,  3.5 ],
       [ 0.  ,  0.  ,  0.  ,  0.  ]])