In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.loadtxt('solve_sretro.txt')
nC = len(A[0])
b = [row[nC-1] for row in A]
print(A)
print(A[0])
b

[[ 3. -4.  1.  9.]
 [ 1.  2.  2.  3.]
 [ 4.  0. -3. -2.]]
[ 3. -4.  1.  9.]


[9.0, 3.0, -2.0]

In [3]:
# plt.plot(x,y,'o:r')
plt.plot(x,z,'b')


NameError: name 'x' is not defined

In [ ]:
x = 2
y = 10
print(x,y)

x,y = y,x
print(x,y)


2 10
10 2


In [ ]:
def algo(x,y):
    return 2*x, 3*y

In [ ]:
i,j = algo(5,6)
print(i,j)

10 18
