# Matemática Computacional - Trabalho 1

## Equipe:
* Henricky de  Lima Monteiro - 475075
* João Almir da Costa Junior - 470034
* 



In [1]:
#base imports
import numpy as np
import matplotlib.pyplot as plt

------------------------
### Q1) Implementar:
#### a) Eliminação de Gauss

Inicialmente vamos escrever a substituição retroativa para testar o método de Gauss.

In [2]:
# Substituição Retroativa
"""
A - matriz extendida
nEq - ordem da matriz
nL - num linhas
nC - num colunas
x - solução
"""
def sretro(A):
    nC = len(A[0])
    nEq = nC-1
    b = [row[nC-1] for row in A]
    x = np.zeros(nEq)
    for i in range(nEq,0,-1):
        I = i-1
        x[I]=b[I]
        sumRes = 0
        #aux = "x[{0}] = b[{0}] - (".format(I)
        for j in range(i,nEq):
         #   aux += "A[{0}][{1}]*x[{1}]".format(I,j)
            sumRes = sumRes + A[I][j]*x[j]
        #aux += ') / A[{0}][{0}]'.format(I)
        #print(aux)
        if(A[I][I] != 0):
            x[I] = (x[I]-sumRes)/A[I][I]
        elif(x[I]-sumRes != 0):
            raise Exception("Impossible system")
        else:
            raise Exception("Indeterminate system")
    return x

Agora vamos implementar a eliminação de gauss da forma simples, sem pivoteamento.

In [3]:

"""
A - matriz extendida
nEq - ordem da matriz
nL - num linhas
nC - num colunas
x - solução
"""
def gauss(A):
    nL= len(A)
    nC = len(A[0])
    nEq = nC-1
    posPivo=0
    for i in range(0,nEq-1):
        pivo = A[i][i]
        posPivo=i
        # calc multiples
        m = np.zeros(nL)
        for k in range(i+1,nL):
#            print('m[{0}] = - A[{0}][{1}]/A[{0}][{0}]'.format(k,0),"= -{0}/{1}".format(A[k][0],pivo))
            m[k] = - A[k][posPivo]/pivo
        # Operações
        for j in range(posPivo+1,nL):
            #print('L({0})={1}, m({0})={2}'.format(j,A[j],m[j]))
            A[j] = m[j]*A[posPivo]+A[j]
    return A

#### b) Métodos de Jacobi e Gauss-Seidel

In [4]:
def ajustePivoteamento(A):
    for i in range(len(A)):
        pivo = A[i][i]
        col = [row[i] for row in A]
        if( pivo < 1 and pivo >-1):
            indexMax = col.index(max(col))
            A[[i,indexMax]] = A[[indexMax,i]]
    return A
    
A = np.array([[0,2,3],[4,0.1,6],[7,8,-0.9]])
print(A)
res=ajustePivoteamento(A)
print(res)


[[ 0.   2.   3. ]
 [ 4.   0.1  6. ]
 [ 7.   8.  -0.9]]
[[ 4.   0.1  6. ]
 [ 7.   8.  -0.9]
 [ 0.   2.   3. ]]


In [5]:

def EqGeral(A):
    nL= len(A)
    nC = len(A[0])
    nEq = nC-1
    eG = []
    b = np.zeros(3)
    
    for i in range(nL):
        aux = []
        for j in range(nC):
            if(i==j):
                aux.append(None)         
            elif(j == nC-1):
                continue
            else:
                aux.append(A[i][j]*-1)    
        eG.append(aux.copy())
        aux.clear()

    return np.array(eG)

EqGeral(np.loadtxt("ex_jacobi.txt"))

    

array([[None, 1.0],
       [-1.0, None]], dtype=object)

In [11]:
# Método de Jacobi
"""
A - matriz extendida
nEq - ordem da matriz
nL - num linhas
nC - num colunas
x - solução
"""


def Jacobi(A,E,k=0, maxK=15, X0=None):
    nL= len(A)
    nC = len(A[0])
    #get b's - independentes
    b = [row[nC-1] for row in A]
    #divisores
    div = A.diagonal()
    #definindo x0 - solução
    Xa = np.zeros(nC-1) #X_anterior - X0
    #define a solução
    X = np.zeros(nC-1) 
    if(X0.any()):
        for i in range(len(b)):
            Xa[i]= b[i]/div[i]
    else:
        Xa = X0
    #pega a equação geral
    EG = EqGeral(A)
    #Aplicando
    # print('#',max(X-Xa))
    for i in range(nL):
        soma = b[i]
        for j in range(nC-1):
            termo = EG[i][j]
            if(termo != None):
                xj = Xa[j]
                soma += xj*termo
        X[i] = soma/div[i]
    # print('X',X)
    while(max(X-Xa) > E ):
        Xa = X
        X = np.zeros(nC-1) 
        k=k+1
        if(k> maxK):
            break
        for i in range(nL):
            soma = b[i]
            for j in range(nC-1):
                termo = EG[i][j]
                if(termo != None):
                    xj = Xa[j]
                    soma += xj*termo
            X[i] = soma/div[i]
        print('->',max(X-Xa))
        print('X',X, 'k: ', k)


    print('>>>',max(X-Xa))
        
    
    return X

Jacobi(np.loadtxt("ex_jacobi.txt"),-10,X0=np.array([0,0]))

-> 0.75
X [1.25 1.25] k:  1
-> -0.125
X [1.125 0.875] k:  2
-> 0.0625
X [0.9375 0.9375] k:  3
-> 0.09375
X [0.96875 1.03125] k:  4
-> 0.046875
X [1.015625 1.015625] k:  5
-> -0.0078125
X [1.0078125 0.9921875] k:  6
-> 0.00390625
X [0.99609375 0.99609375] k:  7
-> 0.005859375
X [0.99804688 1.00195312] k:  8
-> 0.0029296875
X [1.00097656 1.00097656] k:  9
-> -0.00048828125
X [1.00048828 0.99951172] k:  10
-> 0.000244140625
X [0.99975586 0.99975586] k:  11
-> 0.0003662109375
X [0.99987793 1.00012207] k:  12
-> 0.00018310546875
X [1.00006104 1.00006104] k:  13
-> -3.0517578125e-05
X [1.00003052 0.99996948] k:  14
-> 1.52587890625e-05
X [0.99998474 0.99998474] k:  15
>>> -0.9999847412109375


array([0., 0.])

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A[1][1] = -5
A

array([[ 1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8,  9]])

In [ ]:
a = None